from snakemake.utils import min_version

min_version("7.15.2")

configfile: "config.yaml"

rule init:
    input: 
        param = "data/parameters.txt",
        infile = config["infile"]
        query = config["query"]
        outdir = config["outdir"] 
        hostfile = config["hostfile"]
    output:
        dico_data_update = temp("results/data.pkl"),
        dico_params_update = temp("results/params.pkl")
    shell:
        "python3 scripts/init_test.py -p {input.param} -i {input.infile} -q {input.query} -o {input.outdir} -h {input.hostfile}"


rule blast:
    input: 
        dico_params = "results/params.pkl", #ne va pas parce que j'aurai ça dans tous les cas
        dico_data = "results/data.pkl" #ne va pas 
        blastfile = 'results/blast_' + fastafile
    output:
        dico_data_update = temp("results/data_blast.pkl"), # ne vas pas
        dico_params_update = "results/params_blast.pkl" #ne va pas 
    shell:
        "python3 scripts/blast_test.py {input.dico_params} {input.dico_data} {output.dico_data_update} {output.dico_params_update}"


rule extract:
    input: 
        tsvfile = 
        dico_data = "results/data_blast.pkl"
    output:
        dico_data_update = temp("results/data_extract.pkl"),
        accns = "results/accns.txt"
    shell:
        "python3 scripts/extract_test.py {input.dico_data} {output.accns} {output.dico_data_update}"


rule fasta_res:
    input: 
        dico_params = "results/params_blast.pkl",
        dico_data = "results/data_extract.pkl"
    output:
        dico_data_update = "results/data_fastaRes.pkl",
        seq = "results/sequences.fasta"
    shell:
        "python3 scripts/fastares_test.py {input.dico_params} {input.dico_data} {output.seq} {output.dico_data_update}"

