rule blast :
    input : 
        "data/ex_CCDS.fasta"
    output :
        "results/blastres.tsv"
    script :
        "scripts/blast_test.py"

rule extract : 
    input :
        "results/blastres.tsv"
    output :
        "results/accns.txt"
    script :
        "scripts/extract_test.py"

rule fasta :
    input :
        "results/blastres.tsv",
        "data/ex_CCDS.fasta",
        "data/ex_spTree.tree"
    output :
        "results/sequences.fasta"
    script :
        "scripts/fastares_test.py"
