from snakemake.utils import min_version, validate
min_version("7.15.2")

configfile: "config/config.json"
validate(config, "config/config.schema.yaml")

rule init:
    input: 
        config = "config/config.json"
    output:
        infile = config["data"]["o"]+config["parameters"]["step"]+"_"+[config["parameters"]["infile"]][0].split("/")[1]
    shell:
        "python3 scripts/init_test.py {input.config} {output.infile}"


rule blast:
    input:
        infile = config["data"]["o"]+"blast_{samples}.fasta"
    output:
        tsvfile = config["data"]["o"]+"{samples}_blastres.tsv"
    params:
        config = "config/config.json"
    shell:
        "python3 scripts/blast_test.py {params.config} {output.tsvfile}"


rule extract:
    input:
        blastres = config["data"]["o"]+"{samples}_blastres.tsv" # à remplacer par config["data"]["o"]+"{samples}.tsv" car tous les fichiers d'entrée n'auront pas '_blastres'
    output:
        accns = "results/{samples}_accns.txt" #à modifier quand samples aura changé 
    params:
        config = "config/config.json"
    shell:
        "python3 scripts/extract_test.py {params.config} {input.blastres} {output.accns}"


rule fasta_res:
    input: 
        accns = "results/{samples}_accns.txt" #pareil que pour input extract 
    output:
        seq = "results/{samples}_sequences.fasta"
    params:
        config = "config/config.json"
    shell:
        "python3 scripts/fastares_test.py {params.config} {input.accns} {output.seq}"

"""

rule get_orf:
    input:
        seqfile = "results/{samples}_sequences.fasta" #pareil que pour input extract 
    output:
        res = "results/{samples}_allORFs.fasta",
        res_longest = "results/{samples}_longestORFs.fasta"
    params:
        config = "config/config.json",
    shell:
        "python3 scripts/orf_test.py {params.config} {output.res} {output.res_longest}"


rule align_prank: 
    input:
        lgst_ORFs = "results/{samples}_longestORFs.fasta"
    output:
        out_codon = "results/{samples}_ORFs_alcodon_prank.fas", #ajouter tree dans le nom
        out_mafft = "results/{samples}_ORFs_al_mafft.fasta",
        out_covAln = "results/{samples}_ORFs_al_mafft_clean.fasta"
        # data_update_mafft = "results/data_mafft.pkl",
        # data_update_codon = "results/data_prank.pkl"
    params:
        extension = config["parameters"]["codon_aligner"],                     # Seconde partie du nom du fichier de sortie
        out_codon_param = "results/{samples}_ORFs_alcodon",     # Première partie du nom du fichier de sortie
        config = "config/config.json"
    run:
        shell("mafft --auto --quiet {input.lgst_ORFs} > {output.out_mafft}"),
        shell("python3 scripts/covAln_test.py {output.out_mafft} {output.out_covAln} {params.config}"),  #in1 : alignement mafft
                                                                                                        #in2 : fichier où covAln output
                                                                                                        #in3 : dictionnaire config
                                                                                                        # Data est update au sein de ce script
        shell("prank -d={output.out_covAln} -o={params.out_codon_param}_{params.extension}.fas -codon -F"),
        shell("python3 scripts/data_update_alcodon.py {params.out_codon_param}_{params.extension}.fas {params.config} {params.extension}")  #update de config["data"]["aln"] pour qu'il contienne le chemin
                                                                                                                                    #vers le fichier de sortie de prank.
                                                                                                                                    #Passage de {extension} pour verbose.

"""

rule align_macse: 
    input:
        lgst_ORFs = "results/{samples}_longestORFs.fasta"
    output:
        out_codon = "results/{samples}_ORFs_alcodon_macse.fas", #ajouter tree dans le nom
        out_mafft = "results/{samples}_ORFs_al_mafft.fasta",
        out_covAln = "results/{samples}_ORFs_al_mafft_clean.fasta"
        # data_update_mafft = "results/data_mafft.pkl",
        # data_update_codon = "results/data_prank.pkl"
    params:
        extension = config["parameters"]["codon_aligner"],                     # Seconde partie du nom de fichier de sortie
        out_codon_param = "results/{samples}_ORFs_alcodon",     # Première partie du nom de fichier de sortie
        config = "config/config.json"
    run:
        shell("mafft --auto --quiet {input.lgst_ORFs} > {output.out_mafft}"),
        shell("python3 scripts/covAln_test.py {output.out_mafft} {output.out_covAln} {params.config}"),  #in1 : alignement mafft
                                                                                                        #in2 : fichier où covAln output
                                                                                                        #in3 : dictionnaire config
                                                                                                        # Data est update au sein de ce script

        shell("java -jar ../macse_v2.06.jar -prog refineAlignment -align {output.out_covAln} -out_NT {params.out_codon_param}_{params.extension}.fas"),
        shell("python3 scripts/data_update_alcodon.py {params.out_codon_param}_{params.extension}.fas {params.config} {params.extension}")  #update de config["data"]["aln"] pour qu'il contienne le chemin
                                                                                                                                    #vers le fichier de sortie de prank.
#manque des conditions d'entrée cf DGINN.py 

rule tree:
    input:
        infile = "results/ex_CCDS_ORFs_alcodon_macse.fas" #ajouter tree dans le nom
    params:
        fonction = "phyMLTree",
        config = "config/config.json"
    output:
        phymlfile = config["data"]["o"]+config["data"]["aln"].split("/")[-1].split(".")[0]+".phylip_phyml_tree.txt"
    shell:
        "python3 scripts/analysis_test.py {params.config} {params.fonction}"


rule duplication:
    input:
        infile = "results/ex_CCDS_ORFs_alcodon_macse.fas", #ajouter duplication dans le nom
        infile_tree = config["data"]["dAlTree"][config["data"]["aln"]]
    params:
        fonction = "checkPhyMLTree",
        config = "config/config.json"
    output:
        output_nhx = config["data"]["dAlTree"][config["data"]["aln"]]+"_recs.nhx",
        output_svg = config["data"]["dAlTree"][config["data"]["aln"]]+"_recs.svg"
    shell:
        "python3 scripts/analysis_test.py {params.config} {params.fonction}"
