from snakemake.utils import min_version, validate
min_version("7.15.2")

configfile: "config.json"
validate(config, "config.schema.yaml")
config_file = "config.json"
rule init:
    input: 
        param = config["parameters"],
        infile = config["infile"]
    params:
        query = config["queryName"],
        outdir = config["outdir"],
        hostfile = config["hostfile"]
    output:
        dico_data_update = "results/data.pkl",
        dico_params_update = "results/params.pkl"
    run:
        shell("python3 test.py {params.query} {params.outdir} {params.hostfile} {config_file}")

"""
if '.fasta' in config[infile][files]:
    if len(config[infile][files].split(',')) != 1:
        if '.fasta' in config[infile][files].split(',')[0]:
            fastafile = config[infile][files].split(',')[0]
        elif '.fasta' in config[infile][files].split(',')[1]:
            fastafile = config[infile][files].split(',')[1]
    else :
        fastafile = config[infile][files]
    dest = 'results/'+config[step]+'_'+fastafile
    shutil.copyfile(fastafile, dest)


rule init:
    input: 
        param = config[parameters],
        infile = 'results/blast_'+fastafile #devrait être enlevé
    output:
        dico_data_update = temp("results/data.pkl"),
        dico_params_update = temp("results/params.pkl")
    shell:
        "python3 scripts/init_test.py -p {input.param} -i {input.infile}"
"""