on:
  push:

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

   # container:
   #     image: quay.io/singularity/singularity:v4.1.0
   #     options: --privileged

    name: Build Apptainer Container
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Build Container
        run: |
           apptainer build dginn.sif docker://ghcr.io/lgueguen/dginn:master

      - name: Login and Deploy Container
        run: |
           echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
           apptainer push dginn.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}# Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      
           
