on:
  push:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Build Apptainer Container
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Setup Apptainer
        run: |
           sudo add-apt-repository -y ppa:apptainer/ppa
           sudo apt update
           sudo apt install -y apptainer
  
      - name: Build Container         
        run: |
           apptainer build dginn.sif docker://ghcr.io/lgueguen/dginn:master

      - name: Login and Deploy Container
        run: |
           apptainer registry login --username ${{ secrets.GHCR_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} oras://ghcr.io
           apptainer push dginn.sif oras://ghcr.io/${GITHUB_REPOSITORY}
